<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aldo Sam Muhajir">
<meta name="dcterms.date" content="2023-01-20">

<title>Analisis Pengaruh Ekspor Minyak Kelapa Sawit (CPO) Indonesia ke Negara tujuan India Terhadap Nilai Tukar Rupiah Periode 2012-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#pendahuluan" id="toc-pendahuluan" class="nav-link active" data-scroll-target="#pendahuluan"><span class="toc-section-number">1</span>  Pendahuluan</a>
  <ul class="collapse">
  <li><a href="#latar-belakang" id="toc-latar-belakang" class="nav-link" data-scroll-target="#latar-belakang"><span class="toc-section-number">1.1</span>  Latar belakang</a></li>
  <li><a href="#ruang-lingkup" id="toc-ruang-lingkup" class="nav-link" data-scroll-target="#ruang-lingkup"><span class="toc-section-number">1.2</span>  Ruang lingkup</a></li>
  <li><a href="#rumusan-masalah" id="toc-rumusan-masalah" class="nav-link" data-scroll-target="#rumusan-masalah"><span class="toc-section-number">1.3</span>  Rumusan masalah</a></li>
  <li><a href="#tujuan-dan-manfaat-penelitian" id="toc-tujuan-dan-manfaat-penelitian" class="nav-link" data-scroll-target="#tujuan-dan-manfaat-penelitian"><span class="toc-section-number">1.4</span>  Tujuan dan Manfaat penelitian</a></li>
  <li><a href="#package" id="toc-package" class="nav-link" data-scroll-target="#package"><span class="toc-section-number">1.5</span>  Package</a></li>
  </ul></li>
  <li><a href="#studi-pustaka" id="toc-studi-pustaka" class="nav-link" data-scroll-target="#studi-pustaka"><span class="toc-section-number">2</span>  Studi pustaka</a>
  <ul class="collapse">
  <li><a href="#teori-perdagangan-internasional" id="toc-teori-perdagangan-internasional" class="nav-link" data-scroll-target="#teori-perdagangan-internasional"><span class="toc-section-number">2.1</span>  Teori Perdagangan Internasional</a></li>
  <li><a href="#teori-nilai-tukar" id="toc-teori-nilai-tukar" class="nav-link" data-scroll-target="#teori-nilai-tukar"><span class="toc-section-number">2.2</span>  Teori Nilai Tukar</a></li>
  <li><a href="#pengaruh-ekspor-terhadap-nilai-tukar" id="toc-pengaruh-ekspor-terhadap-nilai-tukar" class="nav-link" data-scroll-target="#pengaruh-ekspor-terhadap-nilai-tukar"><span class="toc-section-number">2.3</span>  Pengaruh Ekspor Terhadap Nilai Tukar</a></li>
  </ul></li>
  <li><a href="#metode-penelitian" id="toc-metode-penelitian" class="nav-link" data-scroll-target="#metode-penelitian"><span class="toc-section-number">3</span>  Metode Penelitian</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="toc-section-number">3.1</span>  Data</a></li>
  <li><a href="#metode-analisis" id="toc-metode-analisis" class="nav-link" data-scroll-target="#metode-analisis"><span class="toc-section-number">3.2</span>  Metode analisis</a></li>
  </ul></li>
  <li><a href="#pembahasan" id="toc-pembahasan" class="nav-link" data-scroll-target="#pembahasan"><span class="toc-section-number">4</span>  Pembahasan</a>
  <ul class="collapse">
  <li><a href="#pembahasan-masalah" id="toc-pembahasan-masalah" class="nav-link" data-scroll-target="#pembahasan-masalah"><span class="toc-section-number">4.1</span>  Pembahasan masalah</a></li>
  <li><a href="#analisis-masalah" id="toc-analisis-masalah" class="nav-link" data-scroll-target="#analisis-masalah"><span class="toc-section-number">4.2</span>  Analisis masalah</a></li>
  </ul></li>
  <li><a href="#kesimpulan-saran" id="toc-kesimpulan-saran" class="nav-link" data-scroll-target="#kesimpulan-saran"><span class="toc-section-number">5</span>  Kesimpulan &amp; Saran</a>
  <ul class="collapse">
  <li><a href="#kesimpulan" id="toc-kesimpulan" class="nav-link" data-scroll-target="#kesimpulan"><span class="toc-section-number">5.1</span>  Kesimpulan</a></li>
  <li><a href="#saran" id="toc-saran" class="nav-link" data-scroll-target="#saran"><span class="toc-section-number">5.2</span>  Saran</a></li>
  </ul></li>
  <li><a href="#referensi" id="toc-referensi" class="nav-link" data-scroll-target="#referensi"><span class="toc-section-number">6</span>  Referensi</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Ekspor Minyak Kelapa Sawit (CPO) Indonesia ke Negara tujuan India Terhadap Nilai Tukar Rupiah Periode 2012-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aldo Sam Muhajir </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">.</figcaption><p></p>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan negara produsen unggulan atau pertama yang mengekspor minyak kelapa sawit atau Crude Palm Oil (CPO) (Syamsulbahri, 1996). Crude Palm Oil (CPO) salah satu komoditas perkebunan ekspor unggulan yang mampu memberikan kontribusi dan sebagai salah satu penyumbang pendapatan devisa Indonesia dari ekspor tersebut. Produk olahan dari kelapa sawit yang kaya akan manfaat mempunyai peluang ekspor yang cukup besar di pasar internasional, selain diolah sebagai bahan baku industri minyak goreng, margarin, sabun dll. Salah satu perkembangan produk turunan minyak kelapa sawit (CPO) adalah bahan bakar minyak, yaitu biodesel yang menjadikannya CPO trending topic untuk kelangsungan energi di masa yang akan datang. Indonesia merupakan Negara penghasil minyak kelapa sawit (CPO) terbesar di dunia dengan rata-rata kontribusi produksi sebesar 44,46% dari total produksi CPO di dunia.</p>
<p>Ekspor merupakan salah satu aktivitas perdagangan internasional yang mempunyai peranan penting bagi perekonomian suatu negara yang dapat menghasilkan devisa dan dapat digunakan untuk membiayai impor dan pembiyaan pembangunan sektor-sektor di dalam negeri. Proses ekspor pada biasanya merupakan aksi buat menghasilkan barang atau komoditas dari dalam negeri untuk memasukannnya ke negara lain melalu prosedur dan tata cara yang di tetapkan oleh pemerintah. Ekspor barang secara besar umumnya membutuhkan campur tangan dari bea cukai di Negara pengirim maupun penerima. Negara tujuan utama ekspor meliputi India, China, Pakistan, Spanyol dan Mesir. Tercatat India merupakan pangsa pasar terbesar ekspor minyak sawit nasional, yakni sebesar US$ 3,11 milliar (11,96%) pada tahun 2021. Sebagai produsen minyak kelapa sawit terbesar di dunia, Indonesia mengekspor minyak kelapa sawit ke India terus mengalami pengingkatan pada tahun 2012-2021.</p>
<p>Dalam melakukan kegiatan perdagangan internasional khususnya ekspor, yang menjadi acuan dalam penentuan tinggi rendahnya harga komoditas tersebut yaitu nilai tukar atau kurs, dimana kurs merupakan perbandingan antara harga mata uang suatu negara dengan negara lainnya. Sehingga ketika nilai mata uang mengalami kenaikan maka akan menguntungkan bagi negara pengekspor begitu pula sebaliknya. Penelitian ini bertujuan untuk mengetahui pengaruh nilai tukar rupiah terhadap nilai ekspor ke negara India dengan periode waktu tahun 2012-2021. Metode penelitian yang digunakan dalam penelitian ini adalah menggunakan metode regresi univariat atau Ordinary Least Square (OLS) dengan menggunakan data time series (2012-2021).</p>
<table class="table">
<caption><strong>Tabel 1: Ekspor Minyak Kelapa sawit Indonesia negara tujuan India periode 2012-2021:</strong></caption>
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Tahun</th>
<th>2012</th>
<th>2013</th>
<th>2014</th>
<th>2015</th>
<th>2016</th>
<th>2017</th>
<th>2018</th>
<th>2019</th>
<th>2020</th>
<th>2021</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ekspor (Ribu Ton)</td>
<td>5,264.0</td>
<td>5,752.4</td>
<td>4,920.4</td>
<td>5,746.0</td>
<td>5,424.6</td>
<td>7,325.1</td>
<td>6,346.2</td>
<td>4,576.6</td>
<td>4,568.7</td>
<td>3,088.7</td>
</tr>
<tr class="even">
<td>Ekspor (Juta US$)</td>
<td>4,846.5</td>
<td>4,375.4</td>
<td>3,694.3</td>
<td>3,224.3</td>
<td>3,449.5</td>
<td>4,901.2</td>
<td>3,561.5</td>
<td>2,252.0</td>
<td>2,987.3</td>
<td>3,337.8</td>
</tr>
</tbody>
</table>
<p><em>Sumber: Badan Pusat Statistik (BPS)</em></p>
<p>Industri perkebunan dan pengolahan kelapa sawit adalah industri kunci bagi perekonomian Indonesia. Ekspor minyak kelapa sawit adalah penghasil devisa yang penting dan industri ini memberikan kesempatan kerja bagi jutaan orang Indonesia. Berdasarkan latar belakang tersebut penelitian ini bertujuan untuk menganalisis perkembangan nilai ekspor minyak kelapa sawit Indonesia tahun 2012 – 2021, pengaruh harga ekspor dan nilai tukar terhadap nilai ekspor minyak kelapa sawit Indonesia tahun 2012 - 2021.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini membahas mengenai pengaruh nilai tukar terhadap ekspor komoditi unggulan Indonesia yaitu minyak kelapa sawit dengan menggunakan data dengan subjek nilai ekspor minyak kelapa sawit (CPO) dari negara Indonesia ke negara India. Data tersebut diambil dari Badan Pusat Statistik (BPS) dengan kurun waktu 9 tahun terakhir yaitu (2012-2021). Data tersebut kemudian dibandingkan dengan nilai tukar rupiah.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang masalah diatas, maka terdapat beberapa indikator yang menjadi rumusan masalah dalam penelitian ini, Adapun rumusan masalah tersebut adalah sebagai berikut :</p>
<ol type="1">
<li><p>Apakah ekspor minyak kelapa sawit atau Crude Palm Oil (CPO) ke negara India dapat mempengaruhi terhadap nilai tukar rupiah tahun 2012 -2021?</p></li>
<li><p>Bagaimana perkembangan ekspor minyak kelapa sawit atau Crude Palm Oil (CPO) ke negara India dari tahun 2012-2021?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan Manfaat penelitian</h3>
<ol type="1">
<li><p>Untuk mengetahui seberapa besar pengaruh ekspor minyak kelapa sawit atau Crude Palm Oil (CPO) ke negara India dapat mempengaruhi nilai tukar rupiah.</p></li>
<li><p>Untuk mengetahui perkembangan ekspor minyak kelapa sawit atau Crude Palm Oil (CPO) ke negara India periode 2012-2021.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">library</span>(WDI) <span class="co"># tambahkan library lain jika diperlukan</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<section id="teori-perdagangan-internasional" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="teori-perdagangan-internasional"><span class="header-section-number">2.1</span> Teori Perdagangan Internasional</h3>
<p>Perdagangan internasional adalah bentuk transaksi perdagangan yang terjadi antara pelaku-pelaku ekonomi antara dua negara atau lebih, baik transaksi berupa barang maupun transaksi berupa jasa. Adapun pelaku ekonomi tersebut dapat beragam, seperti penduduk yang terdiri dari warga negara biasa, perusahaan impor, perusahaan ekspor, perusahaan industri, perusahaan negara, departemen pemerintah, atau pun individu (Sobri: 2000). Kegiatan perdagangan internasional secara umum meliputi kegiatan ekspor dan impor.</p>
<p>Menurut (Murni: 2006), Kegiatan ekspor adalah suatu kegiatan ekonomi menjual produk dalam negeri kepasar diluar negeri. Sedangkan menurut (Sasono: 2013), Ekspor adalah kegiatan menjual produk dari satu negara ke negara lain melewati batas terluar wilayah kepabeanan suatu negara, dengan tujuan mendapatkan devisa yang sangat dibutuhkan negara, menciptakan lapangan kerja bagi pasar tenaga kerja domestik, mendapatkan pemasukan bea keluar dan pajak lainnya, serta menjaga keseimbangan antara arus barang dan arus uang beredar di dalam negeri.</p>
<p>Menurut (Murni: 2006), Menyatakan bahwa impor merupakan kegiatan ekonomi membeli produk luar negeri untuk keperluan atau dipasarkan didalam negeri. Sedangkan menurut (Amir: 2008), kegiatan impor adalah upaya seorang pengusaha untuk memenuhi kebutuhannya atas suatu barang yang kurang tersedia di dalam negeri, sehingga terpaksa membelinya dari negara lain, serta membayarnya dengan valuta asing.</p>
</section>
<section id="teori-nilai-tukar" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="teori-nilai-tukar"><span class="header-section-number">2.2</span> Teori Nilai Tukar</h3>
<p>Nilai tukar valuta asing adalah harga satu satuan mata uang dalam satuan mata uang lain. Nilai tukar valuta asing ditentukan dalam pasar valuta asing yaitu pasar tempat berbagai mata uang yang berbeda diperdagangkan (Samuelson &amp; Nordhaus, 2004). Sedangkan menurut (Salvatore: 2016), nilai tukar atau exchange rate didefinisikan sebagai harga mata uang luar negeri dalam satuan harga mata uang domestik. Nilai tukar memiliki peranan yang penting dalam perdagangan internasional karena nilai tukar digunakan untuk membandingkan harga barang dan jasa yang terdapat di berbagai negara. Perubahan terhadap nilai tukar disebut sebagai depresiasi dan apresiasi. Nilai tukar dikatakan mengalami depresiasi apabila harga mata uang domestik melemah terhadap mata uang asing sedangkan nilai tukar dikatakan mengalami apresiasi apabila harga mata uang domestik menguat terhadap mata uang asing.</p>
</section>
<section id="pengaruh-ekspor-terhadap-nilai-tukar" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="pengaruh-ekspor-terhadap-nilai-tukar"><span class="header-section-number">2.3</span> Pengaruh Ekspor Terhadap Nilai Tukar</h3>
<p>Berdasarkan teori pendekatan perdagangan yang dikemukakan oleh (Salvatore: 2016), kegiatan ekspor dapat mempengaruhi nilai tukar mata uang. Kegiatan ekspor yang meningkat akan mengakibatkan naiknya permintaan terhadap mata uang negara pengekspor. Kenaikan permintaan terhadap mata uang pengekspor menyebabkan mata uang dalam negeri akan menguat dan mata uang luar negeri akan melemah.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Metode analisis pada penelitian ini menggunakan metode dengan mengambil data sekunder. Data pada analisis penelitian ini dicatat secara sistematis yang berbentuk data runtun waktu (<em>time series data</em>) dari tahun 2012-2021 berdasarkan nilai ekspor minyak kelapa sawit Indonesia ke India dan nilai tukar rupiah terhadap nilai mata uang Rupee India. Adapun sumber data yang diperoleh berasal dari Badan Pusat Statistik (BPS).</p>
<table class="table">
<caption><strong>Tabel 2: Data nilai ekspor minyak kelapa sawit ke negara India dan nilai tukar rupiah.</strong></caption>
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Nilai Ekspor (Rupee)</th>
<th style="text-align: center;">Nilai Tukar (IDR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">395467</td>
<td style="text-align: center;">73548303</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">357026</td>
<td style="text-align: center;">66399101</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">301449</td>
<td style="text-align: center;">56063034</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">263098</td>
<td style="text-align: center;">48930525</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">281474</td>
<td style="text-align: center;">52348059</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">399931</td>
<td style="text-align: center;">74378405</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">290613</td>
<td style="text-align: center;">54047721</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">183760</td>
<td style="text-align: center;">34175338</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">243759</td>
<td style="text-align: center;">45333920</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">272359</td>
<td style="text-align: center;">50652950</td>
</tr>
</tbody>
</table>
<p><em>Sumber : Badan Pusat Statistik (BPS)</em></p>
<section id="hasil-plot" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="hasil-plot"><span class="header-section-number">3.1.1</span> Hasil Plot</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Aldo Sam Muhajir/Documents/KULIAH/Metopel quarto"</span>)</span>
<span id="cb2-2"><a href="#cb2-2"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb2-5"><a href="#cb2-5"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>X,<span class="at">ylab=</span><span class="st">"Nilai Tukar"</span>,<span class="at">xlab=</span><span class="st">"Nilai Ekspor"</span>)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="hasil-plot-dengan-error" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="hasil-plot-dengan-error"><span class="header-section-number">3.1.2</span> Hasil Plot Dengan Error</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Aldo Sam Muhajir/Documents/KULIAH/Metopel quarto"</span>)</span>
<span id="cb3-2"><a href="#cb3-2"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-4"><a href="#cb3-4"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"nilai Ekspor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode Kuantitatif digunakan untuk analisis yang dilakukan dengan perhitungan angka-angka yang mempengaruhi variabel X sebagai nilai ekspor minyak kelapa sawit Indonesia ke India dan variabel Y sebagai nilai tukar rupiah terhadap nilai ekspor minyak kelapa sawit ke negara India. Selanjutnya Metode yang digunakan adalah metode regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen yang digunakan untuk menganalisis pengaruh nilai tukar rupiah terhadap nilai ekspor ke negara India. Penelitian ini bermaksud untuk mencari hubungan antara nilai tukar sebagai variabel Y dan nilai ekspor sebagai variabel X. spesifikasi yang dilakukan adalah :</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> Dimana:</p>
<p><span class="math inline">\(y_t\)</span> = Nilai Tukar Rupee (India) terhadap mata uang negara lain</p>
<p><span class="math inline">\(\beta_0\)</span> = Koefisien konstanta</p>
<p><span class="math inline">\(\beta_1\)</span> = Parameter</p>
<p><span class="math inline">\(x_t\)</span> = Nilai ekspor</p>
<p><span class="math inline">\(\mu_t\)</span> = error term</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<caption><strong>Tabel 3: Perkembangan nilai ekspor minyak kelapa sawit di Indonesia ke India periode 2012-2021</strong></caption>
<colgroup>
<col style="width: 26%">
<col style="width: 37%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Nilai Ekspor CPO ke India (Juta US$)</th>
<th style="text-align: center;">Perkembangan (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">4 846.5</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">4 375.4</td>
<td style="text-align: center;">-9.72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">3 694.3</td>
<td style="text-align: center;">-15.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">3 224.3</td>
<td style="text-align: center;">-12.72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">3 449.5</td>
<td style="text-align: center;">6.98</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">4 901.2</td>
<td style="text-align: center;">42.08</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">3 561.5</td>
<td style="text-align: center;">-27.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">2 252.0</td>
<td style="text-align: center;">-36.77</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">2 987.3</td>
<td style="text-align: center;">32.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">3 337.8</td>
<td style="text-align: center;">11.73</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Rata-rata</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-0.87%</td>
</tr>
</tbody>
</table>
<p><em>Sumber: Badan Pusat Statistik (BPS)</em></p>
<p>Tabel 3 memberikan perkembangan nilai ekspor minyak kelapa sawit di Indonesia selama periode tahun 2013-2021. Berdasarkan tabel berikut terlihat bahwa dari tahun 2012 ke 2013 mengalami penurunan sebesar -9,72% dari US$ 4 846.5 pada tahun 2012 menjadi US$ 4 357.4 pada tahun 2013. Perkembangan nilai ekspor minyak kelapa sawit terus menurun , masing-masing sebesar -15.57% pada tahun 2014, pada tahun 2015 menurun -12.72%, kemudian pada tahun 2016 terjadi peningkatan sebesar 6.98% dan di tahun 2017 juga terjadi peningkatan sebesar 42.08%. Setelah itu terjadi penurunan kembali di tahun 2018 sebesar -27.33%, pada tahun 2019 menurun -36.77%, dan terjadi peningkatan di tahun 2020 sebesar 32.65%. Pada tahun 2021 perkembangan nilai ekspor minyak kelapa sawit berakhir dengan peningkatan sebesar 11.73%.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p><strong>Hasil pengaruh jumlah ekspor terhadap nilai tukar menggunakan metode regresi univariat. Hasil Regresinya ditunjukan sebagai berikut :</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-80.134 -11.323   2.433  22.209  70.429 

Coefficients:
             Estimate Std. Error   t value Pr(&gt;|t|)    
(Intercept) 5.446e+01  7.305e+01 7.450e-01    0.477    
X           1.860e+02  2.389e-04 7.784e+05   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 48.71 on 8 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 6.06e+11 on 1 and 8 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Hasil diatas merupakan hasil estimasi OLS dengan menggunakan model regresi univariat. Hasil regresi tersebut digunakan untuk mengetahui hubungan antara variabel X sebagai nilai ekspor minyak kelapa sawit Indonesia ke India dan variabel Y sebagai nilai tukar rupiah terhadap mata uang negara India.</p>
<p>Hasil estimasi didapatkan nilai F-hitung sebesar 0.06e+11 dengan probabilitas &lt;2.2e-16. Koefisien Determinasi (R2) sebesar 1 artinya kontribusi nilai ekspor dan nilai tukar minyak kelapa sawit terhadap nilai ekspor minyak kelapa sawit Indonesia negara tujuan India sebesar 100 persen.</p>
<p>Selanjutnya Interpretasi terhadap masing-masing variabel dalam persamaan diberikan sebagai berikut :</p>
<ol type="1">
<li><em>Variabel X (Nilai Ekspor)</em></li>
</ol>
<p>T-hitung sebesar 7.450e-01 dengan probabilitas 0.477 menunjukan berpengaruh signifikan positif terhadap nilai ekspor minyak kelapa sawit Indonesia negara tujuan India. Dengan koefisien regresi sebesar 5.446e+01, maka peningkatan harga ekspor minyak kelapa sawit Indonesia negara tujuan India sebesar 1 persen menyebabkan peningkatan nilai ekspor minyak kelapa sawit Indonesia negara tujuan India sebesar 5.446e+01 persen.</p>
<ol start="2" type="1">
<li><em>Variabel Y (Nilai Tukar)</em></li>
</ol>
<p>T-Hitung sebesar 7.784e+05 dengan probabilitas &lt;2e-16 menunjukan bahwa nilai tukar tidak berpengaruh signifikan terhadap nilai ekspor minyak kelapa sawit Indonesia negara tujuan India.</p>
</section>
</section>
<section id="kesimpulan-saran" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan-saran"><span class="header-section-number">5</span> Kesimpulan &amp; Saran</h2>
<section id="kesimpulan" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5.1</span> Kesimpulan</h3>
<ol type="1">
<li><p>Berdasarkan hasil penelitian ini, dapat disimpulkan bahwa jumlah ekspor berpengaruh signifikan terhadap nilai tukar.</p></li>
<li><p>Rata-rata perkembangan nilai ekspor minyak sawit Indonesia negara tujuan India selama periode tahun 2012-2021 adalah -0.87 persen.</p></li>
</ol>
</section>
<section id="saran" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="saran"><span class="header-section-number">5.2</span> Saran</h3>
<p>Saran yang bisa penulis berikan kepada pemerintah melalui berbagai kebijakannya hendaknya dapat menjaga kestabilan harga serta berupaya selalu meningkatkan kualitas serta kuantitas ekspor minyak kelapa sawit atau Crude Palm Oil (CPO).</p>
</section>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Ewaldo, E. (2015). Analisis ekspor minyak kelapa sawit di Indonesia. E-Journal Perdagangan Industri Dan Moneter, 3(1), Article 1. https://doi.org/10.22437/pim.v3i1.3988</p>
<p>Badan Pusat Statistik. (n.d.). Retrieved January 20, 2023, from https://www.bps.go.id/statictable/2014/09/08/1026/ekspor-minyak-kelapa-sawit-menurut-negara-tujuan-utama-2012-2021.html</p>
<p>Taufiq, M., &amp; Natasah, N. A. (2019). Analisis Pengaruh Nilai Tukar Terhadap Ekspor Komoditas Unggulan Indonesia. JDEP (Jurnal Dinamika Ekonomi Pembangunan), 2(1), Article 1. https://doi.org/10.33005/jdep.v2i1.85</p>
<p>Dewi, N. PENGARUH EKSPOR, IMPOR, INFLASI, DAN PERTUMBUHAN EKONOMI TERHADAP NILAI TUKAR DI INDONESIA. Jurnal Ekonomi Daerah (JEDA), 8(2).</p>
<p>Wahyuningsih, S. N., Budiarto, B., &amp; Juarini, J. (2020). Analisis daya saing dan trend ekspor CPO Indonesia di Pasar India dan China. Jurnal Dinamika Sosial Ekonomi, 20(1), 1-13.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>